#ifndef CONSTANTS_H
#define CONSTANTS_H

#define BGCOLOR_G CLITERAL(Color){8, 20, 8, 255}
#define FGCOLOR_G CLITERAL(Color){60, 200, 60, 255}
#define BGCOLOR_A CLITERAL(Color){0x5e, 0x12, 0x10, 0xff}
#define FGCOLOR_A CLITERAL(Color){0xd3, 0x56, 0x00, 0xff}

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 800
#define TARGET_FPS 60

#define MAX_INPUT_CHARS 64
#define MAX_OUTPUT_LINE 64
#define MAX_OUTPUT_LINES 50
#define MAX_OUTPUT_LINE_LENGHT 128
#define MAX_STATUS_TEXT 100
#define MAX_MODULE_NAME 16
#define MAX_HOST_NAME 7
#define MAX_COMPONENT_NAME 16

#define MAX_PROMPT_CHARS 7 + MAX_HOST_NAME

#define GLOBAL_PADDING 4
#define INTERN_PADDING 2
#define FONT_SIZE 32
#define TITLE_FONT_SIZE FONT_SIZE
#define LINES_SPACING 4

#define MAX_MODULE_NAME_LENGHT 16
#define MAX_AUXILIARY_POWERED_MODULES 2
#define MAX_POWERED_MODULES 12

#define SCREEN_LINES_HEIGHT 2
#define SCREEN_LINES_BGCOLOR CLITERAL(Color){0, 0, 0, 100}
#define SCREEN_LINES_FGCOLOR CLITERAL(Color){255, 255, 255, 100}
#define SCREEN_ANIMATION_TRIGGER 0
#define SCREEN_ANIMATION_SPEED 16.f
#define SCREEN_FISHEYE_STRENGTH 0.5f
#define SCREEN_FISHEYE_SEGMENTS 48

#define CRT_CURVATURE 0.08f
#define CRT_SCANLINE_ALPHA 0.1f
#define CRT_VIGNETTE 0.2f
#endif
